retailops_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: retailops
      password: retailops123
      port: 5432
      dbname: retailops
      schema: analytics
      threads: 4
