AWSTemplateFormatVersion: "2010-09-09"

Description: >- 
    Reatailops - IAM role for pipelines/Athena/Glue/S3
    Prnicipals who can Assume this role: Ouadmin
    Data lake bucket permissions
Parameters:
  ProjectNameInput:
    Type: String
    Default: "retailops"
  Env:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]


Resources:
  RetailOpsPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:  !Sub  "${ProjectNameInput}-${Env}-pipeline-role"
      Path: !Sub  "/retailops/${Env}/"
      Description:  least priviliage IAM role for Athena/Glue/S3
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: AllowOuadminAssumeRole
          Effect: Allow
          Action:
            - 'sts:AssumeRole'
          Principal: 
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/ouadmin"


      Tags: 
       - Key: Project
         Value: !Ref ProjectNameInput
       - Key: ManagedBy
         Value: cloudformation 
          
  RetailOpsPipelinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub  "${ProjectNameInput}-${Env}-pipeline-policy"
      Roles: 
        - !Ref RetailOpsPipelineRole
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:

          #  S3: Data Lake bucket access
          - Sid: S3DataLakeBucketList
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:  !ImportValue retailops-DataLakeBucketARN

          #  S3: Data Lake Data RW
          - Sid: S3DataLakeDataRW
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: 
              - !Sub
                - "${BucketArn}/*"
                - BucketArn: !ImportValue retailops-DataLakeBucketARN

          #  S3: ATHENA BUCKET ACCESS
          - Sid: S3AthenaBucketList
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:  !ImportValue AthenaQueryResultsBucketARN
    

          #  3: Athena results RW
          - Sid: S3AthenaBucketRW
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: 
              - !Sub
                - "${BucketArn}/*"
                - BucketArn: !ImportValue AthenaQueryResultsBucketARN

          # Athena: run queries and read status/results
          - Sid: AthenaQueryExecution
            Effect: Allow
            Action:
              - athena:StartQueryExecution
              - athena:GetQueryExecution
              - athena:GetQueryResults
              - athena:StopQueryExecution
              - athena:GetWorkGroup
              - athena:ListWorkGroups
            Resource: "*"

          # Glue: read Data Catalog (Athena tables live here)
          - Sid: GlueDataCatalogRead
            Effect: Allow
            Action:
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:GetTable
              - glue:GetTables
              - glue:GetPartition
              - glue:GetPartitions
            Resource: "*"

Outputs:
  RetailOpsPipelineRoleARN:
    Description: "RetailOpsPipelineRole Arn"
    Value: !GetAtt RetailOpsPipelineRole.Arn
    Export:
      Name: !Sub "${ProjectNameInput}-${Env}-PipelineRoleArn"
