AWSTemplateFormatVersion: "2010-09-09"
Description: "RetailOps Step Functions pipeline (Lambda -> ECS dbt -> Athena -> SNS) + daily EventBridge schedule"

Parameters:
  ProjectNameInput:
    Type: String
    Default: retailops
  # Networking for Fargate
  SubnetA:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0102629bea446df37

  SubnetB:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-02104ad72813ea4fd

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-06157c5d80a25050e

  #  failure email subscription
  FailureEmail:
    Type: String
    Default: "jawid00786@gmail.com"

Conditions:
  HasFailureEmail: !Not [!Equals [!Ref FailureEmail, ""]]

Resources:

  # SNS Topics
  PipelineSuccessTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ProjectNameInput}-pipeline-success"
      DisplayName: "RetailOps Pipeline Success"

  PipelineFailureTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ProjectNameInput}-pipeline-failure"
      DisplayName: "RetailOps Pipeline Failure"

  FailureEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasFailureEmail
    Properties:
      Protocol: email
      TopicArn: !Ref PipelineFailureTopic
      Endpoint: !Ref FailureEmail

  # Step Functions IAM Role
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectNameInput}-sfn-exec-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RetailOpsPipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !ImportValue retailops-DataGeneratorLambdaArn

              - Effect: Allow
                Action:
                  - ecs:RunTask
                  - ecs:StopTask
                  - ecs:DescribeTasks
                Resource: "*"

              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"

              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                Resource: "*"

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub
                    - "${BucketArn}/*"
                    - BucketArn: !ImportValue AthenaQueryResultsBucketARN

              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Ref PipelineSuccessTopic
                  - !Ref PipelineFailureTopic

  # State machine: GenerateData -> RunDbt -> AthenaValidation -> NotifySuccess
  RetailOpsPipelineStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${ProjectNameInput}-daily-pipeline"
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionString: !Sub
        - |
          {
            "Comment": "RetailOps pipeline: Lambda -> ECS dbt -> Athena -> SNS",
            "StartAt": "GenerateData",
            "States": {
              "GenerateData": {
                "Type": "Task",
                "Resource": "arn:aws:states:::lambda:invoke",
                "Parameters": {
                  "FunctionName": "${DataGenArn}",
                  "Payload": { "date.$": "$.date" }
                },
                "ResultPath": "$.dataGen",
                "Next": "RunDbt",
                "Catch": [
                  { "ErrorEquals": ["States.ALL"], "ResultPath": "$.error", "Next": "NotifyFailure" }
                ]
              },

              "RunDbt": {
                "Type": "Task",
                "Resource": "arn:aws:states:::ecs:runTask.sync",
                "Parameters": {
                  "Cluster": "${DbtClusterArn}",
                  "TaskDefinition": "${DbtTaskDefinitionArn}",
                  "LaunchType": "FARGATE",
                  "NetworkConfiguration": {
                    "AwsvpcConfiguration": {
                      "Subnets": ["${SubnetA}", "${SubnetB}"],
                      "SecurityGroups": ["${SecurityGroupId}"],
                      "AssignPublicIp": "ENABLED"
                    }
                  }
                },
                "ResultPath": "$.dbt",
                "Next": "AthenaValidation",
                "Catch": [
                  { "ErrorEquals": ["States.ALL"], "ResultPath": "$.error", "Next": "NotifyFailure" }
                ]
              },

              "AthenaValidation": {
                "Type": "Task",
                "Resource": "arn:aws:states:::athena:startQueryExecution.sync",
                "Parameters": {
                  "QueryString": "SELECT max(sale_date) AS latest_sale_date, count(*) AS rows_last_7_days FROM retailops_marts.fct_daily_sales WHERE sale_date >= current_date - interval '7' day",
                  "WorkGroup": "${WorkGroupName}",
                  "ResultConfiguration": {
                    "OutputLocation": "s3://${AthenaResultsBucket}/quality-checks/"
                  }
                },
                "ResultPath": "$.athenaCheck",
                "Next": "NotifySuccess",
                "Catch": [
                  { "ErrorEquals": ["States.ALL"], "ResultPath": "$.error", "Next": "NotifyFailure" }
                ]
              },

              "NotifySuccess": {
                "Type": "Task",
                "Resource": "arn:aws:states:::sns:publish",
                "Parameters": {
                  "TopicArn": "${SuccessTopicArn}",
                  "Subject": "RetailOps Pipeline Success",
                  "Message.$": "States.Format('Pipeline succeeded. date={}', $.date)"
                },
                "End": true
              },

              "NotifyFailure": {
                "Type": "Task",
                "Resource": "arn:aws:states:::sns:publish",
                "Parameters": {
                  "TopicArn": "${FailureTopicArn}",
                  "Subject": "RetailOps Pipeline FAILED",
                  "Message.$": "States.Format('Pipeline failed. error={}', $.error)"
                },
                "Next": "FailState"
              },

              "FailState": {
                "Type": "Fail",
                "Error": "RetailOpsPipelineFailed",
                "Cause": "See Step Functions execution + CloudWatch logs"
              }
            }
          }
        - {
            DataGenArn: !ImportValue retailops-DataGeneratorLambdaArn,
            DbtClusterArn: !ImportValue retailops-DbtClusterArn,
            DbtTaskDefinitionArn: !ImportValue retailops-DbtTaskDefinitionArn,
            WorkGroupName: !ImportValue retailops-AthenaWorkGroupName,
            AthenaResultsBucket: !ImportValue AthenaQueryResultsBucketName,
            SuccessTopicArn: !Ref PipelineSuccessTopic,
            FailureTopicArn: !Ref PipelineFailureTopic,
            SubnetA: !Ref SubnetA,
            SubnetB: !Ref SubnetB,
            SecurityGroupId: !Ref SecurityGroupId
          }

  # EventBridge role to start state machine
  EventBridgeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectNameInput}-eventbridge-sfn-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartStateMachine
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !GetAtt RetailOpsPipelineStateMachine.Arn

  # Daily trigger at 06:00 UTC
  DailyPipelineTrigger:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${ProjectNameInput}-daily-trigger"
      Description: "Trigger RetailOps pipeline daily at 06:00 UTC"
      ScheduleExpression: "cron(0 6 * * ? *)"
      State: ENABLED
      Targets:
        - Id: !Sub "${ProjectNameInput}-daily-pipeline-target"
          Arn: !GetAtt RetailOpsPipelineStateMachine.Arn
          RoleArn: !GetAtt EventBridgeExecutionRole.Arn
          Input: "{}"


Outputs:
  StateMachineArn:
    Description: "State machine ARN"
    Value: !GetAtt RetailOpsPipelineStateMachine.Arn
    Export:
      Name: retailops-StateMachineArn

  PipelineSuccessTopicArn:
    Description: "SNS topic ARN for success notifications"
    Value: !Ref PipelineSuccessTopic
    Export:
      Name: retailops-PipelineSuccessTopicArn

  PipelineFailureTopicArn:
    Description: "SNS topic ARN for failure notifications"
    Value: !Ref PipelineFailureTopic
    Export:
      Name: retailops-PipelineFailureTopicArn
