AWSTemplateFormatVersion: "2010-09-09"
Description: RetailOps - ECS Fargate task skeleton for ML pipeline (Step 2)

Parameters:
  ProjectNameInput:
    Type: String
    Default: retailops

  Env:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]

Resources:
  MlTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ProjectNameInput}-${Env}-ml-task"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      Cpu: "2048"
      Memory: "4096"
      EphemeralStorage:
        SizeInGiB: 40
      ExecutionRoleArn: !ImportValue retailops-MlTaskExecutionRoleArn
      TaskRoleArn: !ImportValue retailops-MlTaskRoleArn
      ContainerDefinitions:
        - Name: ml
          Image: !ImportValue retailops-MlImageUri
          Essential: true
          Environment:
            - Name: AWS_DEFAULT_REGION
              Value: !Ref AWS::Region
            - Name: DATALAKE_BUCKET
              Value: !ImportValue retailops-DataLakeBucketName
            - Name: ATHENA_RESULTS_BUCKET
              Value: !ImportValue AthenaQueryResultsBucketName
            - Name: ATHENA_WORKGROUP
              Value: !ImportValue retailops-AthenaWorkGroupName
            - Name: ATHENA_DATABASE
              Value: retailops
            - Name: PIPELINE_DATE
              Value: ""
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue retailops-MlLogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ml

Outputs:
  MlTaskDefinitionFamily:
    Description: ECS ML task family (skeleton)
    Value: !Sub "${ProjectNameInput}-${Env}-ml-task"
    Export:
      Name: retailops-MlTaskDefinitionFamily
