AWSTemplateFormatVersion: "2010-09-09"
Description: >- 
  GLUE DATABASE
  GLUE TABLES (inventory,products,sales,shipments,stores,suppliers
  Athena Workgroup (query result location, encryption ...)
  Bucket for athena results
  IAM permissions (for Athena/Glue/S3 access)



Resources:
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput: 
        Name: retailops
        LocationUri: !ImportValue retailops-DataLakeBucketURI
  
  # RAW Products Table/Dimension
  RawProductsTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: retailops
      TableInput: 
        Name: raw_products
        TableType: EXTERNAL_TABLE
        Parameters:
          skip.header.line.count: "1"
          classification: "csv"
        StorageDescriptor:
          Location: !Sub
            - "${BucketUri}/raw/products/"
            - BucketUri: !ImportValue retailops-DataLakeBucketURI
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.serde2.OpenCSVSerde"
            Parameters:
              separatorChar: ","
              quoteChar: "\""
              escapeChar: "\\"
          Columns:
            - Name: product_id
              Type: string
            - Name: product_name
              Type: string
            - Name: category
              Type: string
            - Name: unit_cost
              Type: decimal(10,2)
            - Name: unit_price
              Type: decimal(10,2)
            - Name: supplier_id
              Type: string
            - Name: is_active
              Type: boolean

  # RAW Stores Table/Dimension
  RawStoresTable:
      Type: AWS::Glue::Table
      DependsOn: GlueDatabase
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseName: retailops
        TableInput:
          Name: raw_stores
          TableType: EXTERNAL_TABLE
          Parameters:
            skip.header.line.count: "1"
            classification: "csv"
          StorageDescriptor:
            Location: !Sub
              - "${BucketUri}raw/stores/"
              - BucketUri: !ImportValue retailops-DataLakeBucketURI
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            SerdeInfo:
              SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
              Parameters:
                separatorChar: ","
                quoteChar: "\""
                escapeChar: "\\"
            Columns:
              - Name: store_id
                Type: string
              - Name: store_name
                Type: string
              - Name: region
                Type: string
              - Name: store_type
                Type: string
              - Name: sq_footage
                Type: int
              - Name: opened_date
                Type: date

  # RAW Suppliers Table/Dimension
  RawSuppliersTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: retailops
      TableInput:
        Name: raw_suppliers
        TableType: EXTERNAL_TABLE
        Parameters:
          skip.header.line.count: "1"
          classification: "csv"
        StorageDescriptor:
          Location: !Sub
            - "${BucketUri}raw/suppliers/"
            - BucketUri: !ImportValue retailops-DataLakeBucketURI
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
            Parameters:
              separatorChar: ","
              quoteChar: "\""
              escapeChar: "\\"
          Columns:
            - Name: supplier_id
              Type: string
            - Name: supplier_name
              Type: string
            - Name: lead_time_days
              Type: int
            - Name: on_time_rate
              Type: decimal(5,3)
            - Name: country
              Type: string




Outputs:
  GlueDatabaseName:
    Description: GlueDatabaseName
    Value: !Ref GlueDatabase

  RawProductsTableName:
    Description: RawProducts Table/dimension Name
    Value: !Ref RawProductsTable

  RawStoresTableName:
    Description:  RawStores Table/dimension Name
    Value: !Ref RawStoresTable
  
  RawSuppliersTableName:
    Description:  RawSuppliers Table/dimension Name
    Value: !Ref RawSuppliersTable
